Make temp dir path shorter
One test creates a socket inside of this path. The socket's
path was exceeding the maximum length for socket paths on
macOS. This was causing an error like this:

Error: listen EADDRINUSE /private/var/folders/fg/g0tf_tmx2nzbyb__zps26kx00000gn/T/ancestor-dir11803-61623-hhka6q.es0ra/root-dir1/some.sock

See this build failure: https://circleci.com/gh/atom/atom/6451